CREATE TABLE Person (
    userid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personname VARCHAR(250) UNIQUE,
    dateofbirth INT NOT NULL CHECK
);

INSERT INTO Person (personname, dateofbirth)
VALUES ('Иванов Иван Иванович', 1965),
       ('Петров Пётр Петрович', 1998),
       ('Алексеев Алексей Алексеевич', 2002
);

CREATE TABLE Book (
    bookid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid INT REFERENCES Person(userid) ON DELETE SET NULL,
    bookname VARCHAR(100) NOT NULL,
    author VARCHAR(250) NOT NULL,
    year INT NOT NULL
);

INSERT INTO Book(bookname, author, year)
VALUES ('Дама с собачкой', 'Антон Чехов', 1899),
       ('Чайка', 'Антон Чехов', 1896),
       ('Палата №6', 'Антон Чехов', 1892),
       ('Алгоритмы на Java', 'Роберт Седжвик', 2011),
       ('Комикс Паши Техника', 'Павел Техник', 2023),
       ('Преступление и наказание', 'Фёдор Достоевский', 1866);