
CREATE TABLE Person (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) UNIQUE,
    year INT NOT NULL CHECK ( year > 1900 AND year <= EXTRACT(year FROM now()))
);

INSERT INTO Person (name, year)
VALUES ('Иванов Иван Иванович', 1965),
       ('Петров Пётр Петрович', 1998),
       ('Алексеев Алексей Алексеевич', 2002
);

CREATE TABLE Book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT REFERENCES Person(id) ON DELETE SET NULL,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(250) NOT NULL,
    year INT NOT NULL CHECK ( year > 1564 AND year <= EXTRACT(year FROM now())),
    taken_at TIMESTAMP
);

INSERT INTO Book (title, author, year)
VALUES ('Дама с собачкой', 'Антон Чехов', 1899),
       ('Чайка', 'Антон Чехов', 1896),
       ('Палата №6', 'Антон Чехов', 1892),
       ('Алгоритмы на Java', 'Роберт Седжвик', 2011),
       ('Комикс Паши Техника', 'Павел Техник', 2023),
       ('Преступление и наказание', 'Фёдор Достоевский', 1866);